"""Build a display-only title overlay; never rewrite frozen scholarly snapshots."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    translations = json.loads((ROOT / 'research/classic-title-translations.json').read_text())
    titles = {}
    for domain, names in translations.items():
        papers = json.loads((ROOT / f'research/classics/{domain}.json').read_text())['papers']
        expected = {p['id'].split(':', 2)[2] for p in papers}
        if set(names) != expected:
            raise ValueError(f'{domain}: translations do not match accepted paper identities')
        for paper in papers:
            titles[paper['id']] = {'originalTitle': paper['title'], 'titleZh': names[paper['id'].split(':', 2)[2]]}
    output = ('/* Generated by scripts/sync_classic_titles.py. Display overlay only. */\n'
              '(function(root, titles) {\n'
              "  if (typeof module === 'object' && module.exports) module.exports = titles;\n"
              '  else root.FrontierClassicTitles = titles;\n'
              '})(typeof globalThis !== "undefined" ? globalThis : this, '
              + json.dumps(titles, ensure_ascii=False, indent=2) + ');\n')
    target = ROOT / 'public/assets/classic-titles.js'
    if args.check:
        if not target.exists() or target.read_text() != output:
            raise SystemExit('Classic title overlay is out of date')
    else:
        target.write_text(output)
    print(f'{len(titles)} Chinese titles; frozen catalog and publication files unchanged')


if __name__ == '__main__':
    main()
